#!/usr/bin/env python3
"""Phase 7 Plan 07-02 Task 02 (HARD-16, D-04) -- soak fixture generator.

Emits 50 module_NN.iron files under tests/lsp/soak/fixtures/ totalling
roughly 5000 LoC. Deterministic (seeded PRNG) so regeneration produces
byte-identical output. Committed alongside the .iron files it produces
so operators can re-derive the workspace if needed.

Cross-reference topology:
    - module_01..module_50 each import `module_hub` (fan-in stress for
      the workspace index; exercises references-to-hub hot path).
    - module_hub is module_25.iron (arbitrary; committed alongside).
    - Every module defines 3-5 public funcs; some call siblings.
    - ~100 LoC per module.

This script is committed so operators can regenerate byte-for-byte.
Running it under the default seed MUST produce identical files to
the committed ones. CI parity is enforced by the soak harness
threshold calibration.

Usage:
    python3 tests/lsp/soak/gen_fixtures.py
"""
from __future__ import annotations

import argparse
import pathlib
import random
import sys

N_MODULES = 50
HUB_INDEX = 25
LOC_TARGET = 100

FILE_HEADER = """\
// Phase 7 Plan 07-02 Task 02 (HARD-16, D-04) -- soak fixture.
// Generated by tests/lsp/soak/gen_fixtures.py; do not edit manually.
// Module #{idx:02d}.
"""


def render_module(idx: int, rng: random.Random, n_modules: int = N_MODULES) -> str:
    out: list[str] = []
    out.append(FILE_HEADER.format(idx=idx))

    # Imports. Every module imports module_hub (fan-in). The hub itself
    # imports a few arbitrary siblings (fan-out so references/ quickly
    # traverse a chunk of the graph).
    if idx == HUB_INDEX:
        targets = sorted(rng.sample(
            [i for i in range(1, n_modules + 1) if i != HUB_INDEX], 3))
        for t in targets:
            out.append(f"import module_{t:02d}")
    else:
        out.append(f"import module_{HUB_INDEX:02d}")
    out.append("")

    # Constants.
    out.append(f"val MODULE_ID: Int = {idx}")
    out.append(f"val MODULE_TAG: String = \"module_{idx:02d}\"")
    out.append("")

    # 3-5 public functions.
    n_funcs = rng.randint(3, 5)
    for fi in range(n_funcs):
        name = f"fn_{idx:02d}_{fi}"
        arg_count = rng.randint(1, 3)
        args = ", ".join(f"a{k}: Int" for k in range(arg_count))
        out.append(f"func {name}({args}) -> Int {{")
        # Body: simple arithmetic, maybe calls a sibling.
        body_lines = rng.randint(4, 10)
        out.append(f"  var acc: Int = {rng.randint(0, 99)}")
        for _ in range(body_lines):
            op = rng.choice(["+", "-", "*"])
            rhs_arg = f"a{rng.randint(0, arg_count - 1)}"
            out.append(f"  acc = acc {op} {rhs_arg}")
        # Occasional sibling call (every module except hub calls hub).
        if idx != HUB_INDEX and rng.random() < 0.5:
            out.append(f"  acc = acc + module_{HUB_INDEX:02d}.MODULE_ID")
        out.append("  return acc")
        out.append("}")
        out.append("")

    # Padding helpers to hit ~LOC_TARGET.
    while sum(1 for _ in out) < LOC_TARGET:
        helper_idx = len([l for l in out if l.startswith("func ")])
        out.append(f"func helper_{idx:02d}_{helper_idx}(x: Int) -> Int {{")
        out.append(f"  return x + {rng.randint(1, 100)}")
        out.append("}")
        out.append("")

    return "\n".join(out) + "\n"


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(description=__doc__,
                                  formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--seed", type=int, default=1337)
    here = pathlib.Path(__file__).parent
    p.add_argument("--out-dir", type=pathlib.Path, default=here / "fixtures")
    args = p.parse_args(argv)

    args.out_dir.mkdir(parents=True, exist_ok=True)
    rng = random.Random(args.seed)

    total_loc = 0
    for idx in range(1, N_MODULES + 1):
        # Derive a per-module seed so ordering is deterministic
        # regardless of iteration direction.
        per_rng = random.Random(args.seed * 1000 + idx)
        content = render_module(idx, per_rng)
        (args.out_dir / f"module_{idx:02d}.iron").write_text(content)
        total_loc += content.count("\n")
    print(f"wrote {N_MODULES} .iron files totalling {total_loc} LoC "
          f"under {args.out_dir}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
