#ifndef IRON_RUNTIME_H
#define IRON_RUNTIME_H

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdatomic.h>
#include <pthread.h>

/* ── Iron_String ────────────────────────────────────────────────────────────
 * 24-byte string type with Small String Optimisation (SSO).
 * Strings <= IRON_STRING_SSO_MAX bytes are stored inline without heap
 * allocation. Longer strings are heap-allocated. The intern table
 * deduplicates identical string content for literal strings.
 */
#define IRON_STRING_SSO_MAX 23

typedef struct {
    union {
        /* Heap variant (is_heap flag set) */
        struct {
            char    *data;
            uint32_t byte_length;
            uint32_t codepoint_count;
            uint8_t  _padding[7];
            uint8_t  flags; /* bit 0 = is_heap, bit 1 = is_interned */
        } heap;

        /* SSO variant (is_heap flag clear).
         * data[0..len-1] holds the string bytes; data[len] is always '\0'.
         * data has SSO_MAX+1 slots so a 23-byte string fits with terminator.
         * The union is padded to 25 bytes by the compiler to accommodate this.
         */
        struct {
            char    data[IRON_STRING_SSO_MAX + 1]; /* +1 for null terminator */
            uint8_t len; /* byte length (0..IRON_STRING_SSO_MAX) */
        } sso;
    };
} Iron_String;

/* Iron_String API */
Iron_String  iron_string_from_cstr(const char *cstr, size_t byte_len);
Iron_String  iron_string_from_literal(const char *lit, size_t byte_len);
const char  *iron_string_cstr(const Iron_String *s);
size_t       iron_string_byte_len(const Iron_String *s);
size_t       iron_string_codepoint_count(const Iron_String *s);
bool         iron_string_equals(const Iron_String *a, const Iron_String *b);
Iron_String  iron_string_concat(const Iron_String *a, const Iron_String *b);
Iron_String  iron_string_intern(Iron_String s);

/* ── Iron_Rc / Iron_Weak ─────────────────────────────────────────────────────
 * Atomic reference-counted heap value.  Iron_Weak holds a non-owning
 * reference that returns NULL after the last strong ref is dropped.
 */
typedef struct {
    atomic_int  strong_count;
    atomic_int  weak_count;
    void      (*destructor)(void *value);
} Iron_RcControl;

typedef struct {
    Iron_RcControl *ctrl;
    void           *value;
} Iron_Rc;

typedef struct {
    Iron_RcControl *ctrl;
} Iron_Weak;

Iron_Rc  iron_rc_create(void *value, size_t size, void (*destructor)(void *));
void     iron_rc_retain(Iron_Rc *rc);
void     iron_rc_release(Iron_Rc *rc);
Iron_Weak iron_rc_downgrade(const Iron_Rc *rc);
Iron_Rc  iron_weak_upgrade(const Iron_Weak *weak);

/* ── Iron_Error ──────────────────────────────────────────────────────────────
 * Lightweight error type (no heap allocation).
 */
typedef struct {
    int         code;
    const char *message;
} Iron_Error;

static inline Iron_Error iron_error_none(void)              { return (Iron_Error){0, NULL}; }
static inline Iron_Error iron_error_new(int c, const char *m) { return (Iron_Error){c, m}; }
static inline bool       iron_error_is_ok(Iron_Error e)     { return e.code == 0; }

/* ── Built-in function declarations ──────────────────────────────────────────
 * These are called by code generated by the Iron compiler.
 */
void    Iron_print(Iron_String s);
void    Iron_println(Iron_String s);
int64_t Iron_len(Iron_String s);
int64_t Iron_min(int64_t a, int64_t b);
int64_t Iron_max(int64_t a, int64_t b);
int64_t Iron_clamp(int64_t val, int64_t lo, int64_t hi);
int64_t Iron_abs(int64_t val);
void    Iron_assert(bool cond, Iron_String msg);

/* ── Iron_Pool (fixed-size thread pool) ──────────────────────────────────────
 * Iron_Pool manages a set of worker threads and a FIFO work queue.
 * Iron_pool_barrier() blocks until all submitted work completes.
 * The global pool is initialized in iron_runtime_init().
 */
typedef struct Iron_Pool Iron_Pool;

/* Global pool — initialized in iron_runtime_init() */
extern Iron_Pool *Iron_global_pool;

/* Pool API */
Iron_Pool *Iron_pool_create(const char *name, int thread_count);
void       Iron_pool_destroy(Iron_Pool *pool);
void       Iron_pool_submit(Iron_Pool *pool, void (*fn)(void *), void *arg);
void       Iron_pool_barrier(Iron_Pool *pool);
int        Iron_pool_thread_count(const Iron_Pool *pool);

/* ── Iron_Handle (future for spawn/await) ────────────────────────────────────
 * Created by spawn; awaited with Iron_handle_wait().
 * Panic in the spawned task is stored and re-raised on wait.
 */
typedef struct {
    pthread_t       thread;
    bool            done;
    void           *result;
    pthread_mutex_t lock;
    pthread_cond_t  cond;
    char           *panic_msg;
} Iron_Handle;

/* Handle API */
Iron_Handle *Iron_handle_create(void (*fn)(void *), void *arg);
void         Iron_handle_wait(Iron_Handle *handle);
void         Iron_handle_destroy(Iron_Handle *handle);

/* ── Iron_Channel (bounded ring buffer) ──────────────────────────────────────
 * send blocks when the buffer is full; recv blocks when it is empty.
 * try_recv returns immediately with true/false.
 * capacity 0 or 1 is treated as unbuffered (capacity = 1).
 */
typedef struct Iron_Channel Iron_Channel;

/* Channel API */
Iron_Channel *Iron_channel_create(int capacity);
void          Iron_channel_send(Iron_Channel *ch, void *item);
void         *Iron_channel_recv(Iron_Channel *ch);
bool          Iron_channel_try_recv(Iron_Channel *ch, void **out);
void          Iron_channel_close(Iron_Channel *ch);
void          Iron_channel_destroy(Iron_Channel *ch);

/* ── Iron_Mutex (value-wrapping mutex) ───────────────────────────────────────
 * Wraps a value so that all access must go through lock/unlock.
 * Iron_mutex_lock() returns a pointer to the wrapped value.
 */
typedef struct {
    pthread_mutex_t lock;
    void           *value;
    size_t          value_size;
} Iron_Mutex;

/* Mutex API */
Iron_Mutex *Iron_mutex_create(void *initial_value, size_t size);
void       *Iron_mutex_lock(Iron_Mutex *m);   /* returns pointer to value */
void        Iron_mutex_unlock(Iron_Mutex *m);
void        Iron_mutex_destroy(Iron_Mutex *m);

/* ── Lock / CondVar raw primitives ───────────────────────────────────────────
 * Thin wrappers around pthread_mutex_t and pthread_cond_t for use in
 * Iron programs that need lower-level synchronisation.
 */
typedef pthread_mutex_t Iron_Lock;
typedef pthread_cond_t  Iron_CondVar;

void Iron_lock_init(Iron_Lock *l);
void Iron_lock_acquire(Iron_Lock *l);
void Iron_lock_release(Iron_Lock *l);
void Iron_condvar_init(Iron_CondVar *cv);
void Iron_condvar_wait(Iron_CondVar *cv, Iron_Lock *l);
void Iron_condvar_signal(Iron_CondVar *cv);
void Iron_condvar_broadcast(Iron_CondVar *cv);

/* ── Runtime lifecycle ───────────────────────────────────────────────────────
 * iron_runtime_init() must be called before any Iron_String or Iron_Rc use.
 * It also creates Iron_global_pool with (cpu_count - 1) worker threads.
 * iron_runtime_shutdown() releases all runtime resources.
 */
void iron_runtime_init(void);
void iron_runtime_shutdown(void);

#endif /* IRON_RUNTIME_H */
