/* Generated by Iron compiler (IR backend) */

#include "runtime/iron_runtime.h"
#include "runtime/iron_arena_rt.h"
#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#include <string.h>
#include <stdio.h>
#ifndef _WIN32
#include <unistd.h>
#else
#include <io.h>
#define close _close
#endif
#include "stdlib/iron_math.h"
#define IRON_IO_GENERATED_OBJECTS
#include "stdlib/iron_io.h"
#define IRON_TIMER_STRUCT_DEFINED
#include "stdlib/iron_time.h"
#include "stdlib/iron_log.h"
#include "stdlib/iron_hint.h"
#ifdef __GNUC__
  #define IRON_PREFETCH(addr) __builtin_prefetch(addr, 0, 3)
#elif defined(_MSC_VER)
  #include <xmmintrin.h>
  #define IRON_PREFETCH(addr) _mm_prefetch((const char*)(addr), _MM_HINT_T0)
#else
  #define IRON_PREFETCH(addr) ((void)0)
#endif

typedef struct Iron_Hashable Iron_Hashable;
typedef struct Iron_Set Iron_Set;
typedef struct Iron_List_Iron_Set {
    Iron_Set *items;
    int64_t count;
    int64_t capacity;
} Iron_List_Iron_Set;
typedef struct Iron_Map Iron_Map;
typedef struct Iron_List_Iron_Map {
    Iron_Map *items;
    int64_t count;
    int64_t capacity;
} Iron_List_Iron_Map;
typedef struct Iron_Res Iron_Res;
typedef struct Iron_List_Iron_Res {
    Iron_Res *items;
    int64_t count;
    int64_t capacity;
} Iron_List_Iron_Res;
typedef struct Iron_Bag Iron_Bag;
typedef struct Iron_List_Iron_Bag {
    Iron_Bag *items;
    int64_t count;
    int64_t capacity;
} Iron_List_Iron_Bag;
typedef struct Iron_Inv Iron_Inv;
typedef struct Iron_List_Iron_Inv {
    Iron_Inv *items;
    int64_t count;
    int64_t capacity;
} Iron_List_Iron_Inv;

typedef struct Iron_Hashable Iron_Hashable;
struct Iron_Set {
    int64_t inner;
};
#define IRON_TAG_Iron_Set 8
struct Iron_Map {
    int64_t inner;
};
#define IRON_TAG_Iron_Map 9
struct Iron_Res {
    int64_t n;
};
#define IRON_TAG_Iron_Res 13
struct Iron_Bag {
    Iron_List_Iron_Res items;
};
#define IRON_TAG_Iron_Bag 14
struct Iron_Inv {
    Iron_List_int64_t counts;
};
#define IRON_TAG_Iron_Inv 15

/* Phase 50: Arena-tracked allocation helpers for split collections */
static inline void *_iron_sl_track(void ***tracked_arr, int *count, int *cap, void *ptr) {
    if (!ptr) return NULL;
    if (*count >= *cap) {
        *cap = *cap ? *cap * 2 : 8;
        *tracked_arr = (void **)realloc(*tracked_arr, (size_t)*cap * sizeof(void *));
    }
    (*tracked_arr)[(*count)++] = ptr;
    return ptr;
}
static inline void *_iron_sl_realloc_tracked(void ***tracked_arr, int *count, int *cap, void *old, size_t sz) {
    void *p = realloc(old, sz);
    if (!p) return NULL;
    if (old) {
        for (int i = 0; i < *count; i++) {
            if ((*tracked_arr)[i] == old) { (*tracked_arr)[i] = p; return p; }
        }
    }
    return _iron_sl_track(tracked_arr, count, cap, p);
}
static inline void _iron_sl_free_all(void **tracked, int count) {
    for (int i = 0; i < count; i++) free(tracked[i]);
    free(tracked);
}

typedef enum {
    Iron_Hashable_TAG__NONE = 0,
} Iron_Hashable_Tag;

typedef union {
    char _dummy;
} Iron_Hashable_data_t;

struct Iron_Hashable {
    Iron_Hashable_Tag tag;
    Iron_Hashable_data_t data;
};

/* Split collection for Iron_Hashable */
typedef struct {
    void **_tracked;
    int _tracked_count;
    int _tracked_cap;
    struct { uint8_t tag; int64_t idx; } *_order;
    int64_t _order_count;
    int64_t _order_cap;
    int64_t _total_count;
} Iron_SplitList_Iron_Hashable;

static inline void Iron_SplitList_Iron_Hashable_free(Iron_SplitList_Iron_Hashable *_sl) {
    _iron_sl_free_all(_sl->_tracked, _sl->_tracked_count);
}

IRON_LIST_DECL(Iron_Res, Iron_Res)
static void Iron_Res_drop(Iron_Res *self);
IRON_LIST_IMPL_CORE(Iron_Res, Iron_Res)
Iron_List_Iron_Res Iron_List_Iron_Res_clone(const Iron_List_Iron_Res *src) {
    Iron_List_Iron_Res dst;
    dst.count = src->count;
    dst.capacity = src->count;
    if (src->count > 0) {
        dst.items = (Iron_Res *)malloc((size_t)src->count * sizeof(Iron_Res));
        if (!dst.items) iron_oom_abort("Iron_List_Iron_Res_clone");
        memcpy(dst.items, src->items, (size_t)src->count * sizeof(Iron_Res));
    } else {
        dst.items = NULL;
    }
    return dst;
}
/* Phase 33 STDLIB-02: per-element destructor _free for Iron_Res */
void Iron_List_Iron_Res_free(Iron_List_Iron_Res *self) {
    if (self->items) {
        for (int64_t _i = 0; _i < self->count; _i++) {
            Iron_Res_drop(&self->items[_i]);
        }
    }
    free(self->items);
    self->items = NULL; self->count = 0; self->capacity = 0;
}
void Iron_List_Iron_Res_clear(Iron_List_Iron_Res *self) {
    for (int64_t _i = 0; _i < self->count; _i++) {
        Iron_Res_drop(&self->items[_i]);
    }
    self->count = 0;
}

void __Array_map(Iron_Closure _v1);
void __Array_filter(Iron_Closure _v1);
void __Array_reduce(void* _v1, Iron_Closure _v2);
void __Array_forEach(Iron_Closure _v1);
void __Array_sum(void);
void Iron_res_drop(Iron_Res *_v1);
Iron_Bag Iron_bag_init(Iron_Bag *_v1);
Iron_Inv Iron_inv_init(Iron_Inv *_v1);
Iron_List_int64_t Iron_inv_counts(Iron_Inv _v1);
Iron_List_Iron_Res Iron_make(int64_t _v1);
void Iron_grow(Iron_List_int64_t *_v1, int64_t _v2);
void Iron_main(void);

static inline int64_t Iron_hashable_hash(Iron_Hashable self);
static inline bool Iron_hashable_equals(Iron_Hashable self, Iron_Hashable other);
/* Phase 24 DROP-01: destructor for Iron_Res — static-type dispatch (DROP-03) */
/* Phase 26 POL-06: static dispatch via <TypeName>_rc_drop symbol -- synthesized by emit_ensure_rc_drop in Plan 26-03; called by iron_rc_release on refcount == 0. */
static void Iron_Res_drop(Iron_Res *self) {
    if (!self) return;
    /* user drop body lowered: Iron_Res (Phase 24 DROP-01 / B4) */
    Iron_res_drop(self);
}

static inline Iron_Arena_RT * Iron_arena_new(Iron_Arena_RT * self, int64_t size) {
    (void)self;
    return iron_arena_rt_new((uint64_t)size, false, "arena");
}

static inline Iron_Arena_RT * Iron_arena_new_threadsafe(Iron_Arena_RT * self, int64_t size) {
    (void)self;
    return iron_arena_rt_new((uint64_t)size, true, "arena");
}

static inline Iron_Arena_RT * Iron_arena_with_capacity(Iron_Arena_RT * self, int64_t size) {
    (void)self;
    return iron_arena_rt_new((uint64_t)size, false, "arena");
}

static inline Iron_ArenaSave Iron_arena_save(Iron_Arena_RT * self) {
    return iron_arena_rt_save(self);
}

static inline void Iron_arena_restore(Iron_Arena_RT * self, Iron_ArenaSave point) {
    iron_arena_rt_restore(self, point);
}

static inline void Iron_arena_reset(Iron_Arena_RT * self) {
    iron_arena_rt_reset(self);
}

static inline int64_t Iron_arena_used(Iron_Arena_RT * self) {
    return (int64_t)iron_arena_rt_used(self);
}

static inline int64_t Iron_arena_capacity(Iron_Arena_RT * self) {
    return (int64_t)iron_arena_rt_capacity(self);
}

static inline int64_t Iron_hashable_hash(Iron_Hashable self) {
    switch(self.tag) {
        default: return 0;
    }
}

static inline bool Iron_hashable_equals(Iron_Hashable self, Iron_Hashable other) {
    switch(self.tag) {
        default: return false;
    }
}

void __Array_map(Iron_Closure _v1) {
entry_b1:;
    goto return_exit_0_b2;
return_exit_0_b2:;
    return;
}

void __Array_filter(Iron_Closure _v1) {
entry_b1:;
    goto return_exit_1_b2;
return_exit_1_b2:;
    return;
}

void __Array_reduce(void* _v1, Iron_Closure _v2) {
entry_b1:;
    goto return_exit_2_b2;
return_exit_2_b2:;
    return;
}

void __Array_forEach(Iron_Closure _v1) {
entry_b1:;
    goto return_exit_3_b2;
return_exit_3_b2:;
    return;
}

void __Array_sum(void) {
entry_b1:;
    goto return_exit_4_b2;
return_exit_4_b2:;
    return;
}

/* Phase 24 DROP-01: destructor for Iron_Inv — static-type dispatch (DROP-03) */
/* Phase 26 POL-06: static dispatch via <TypeName>_rc_drop symbol -- synthesized by emit_ensure_rc_drop in Plan 26-03; called by iron_rc_release on refcount == 0. */
static void Iron_Inv_drop(Iron_Inv *self) {
    if (!self) return;
    Iron_List_int64_t_free(&self->counts);
}

/* Phase 24 DROP-01: destructor for Iron_Bag — static-type dispatch (DROP-03) */
/* Phase 26 POL-06: static dispatch via <TypeName>_rc_drop symbol -- synthesized by emit_ensure_rc_drop in Plan 26-03; called by iron_rc_release on refcount == 0. */
static void Iron_Bag_drop(Iron_Bag *self) {
    if (!self) return;
    Iron_List_Iron_Res_free(&self->items);
}

void Iron_res_drop(Iron_Res *_v1) {
    iron_current_dropping_type = "res";
    iron_in_destructor = true;
entry_b1:;
    Iron_String _v3 = iron_string_from_literal("drop ", 5);
    int64_t _v4 = _v1->n;
    Iron_String _v5;
    {
        int _interp_len_5 = snprintf(NULL, 0, "%s%lld", iron_string_cstr(&_v3), (long long)(_v4));
        char *_interp_buf_5 = (char *)malloc((size_t)(_interp_len_5 + 1));
        if (!_interp_buf_5) iron_oom_abort("emit_c interp string");
        snprintf(_interp_buf_5, (size_t)(_interp_len_5 + 1), "%s%lld", iron_string_cstr(&_v3), (long long)(_v4));
        _v5 = iron_string_from_cstr(_interp_buf_5, (size_t)_interp_len_5);
        free(_interp_buf_5);
    }
    Iron_println(_v5);
    goto return_exit_5_b2;
return_exit_5_b2:;
    iron_in_destructor = false;
    return;
}

Iron_Bag Iron_bag_init(Iron_Bag *_v1) {
entry_b1:;
    Iron_Res _v4 = { .n = ((int64_t)1LL) };
    Iron_List_Iron_Res _v5 = Iron_List_Iron_Res_create();
    Iron_List_Iron_Res_push(&_v5, _v4);
    _v1->items = _v5;
    return *_v1;
}

Iron_Inv Iron_inv_init(Iron_Inv *_v1) {
entry_b1:;
    int8_t _v3 = (int64_t)4LL;
    int8_t _v4 = (int64_t)5LL;
    Iron_List_int64_t _v5 = Iron_List_int64_t_create();
    Iron_List_int64_t_push(&_v5, ((int64_t)_v3));
    Iron_List_int64_t_push(&_v5, ((int64_t)_v4));
    _v1->counts = _v5;
    return *_v1;
}

Iron_List_int64_t Iron_inv_counts(Iron_Inv _v1) {
entry_b1:;
    Iron_List_int64_t _v3 = _v1.counts;
    return _v3;
}

Iron_List_Iron_Res Iron_make(int64_t _v1) {
entry_b1:;
    Iron_List_Iron_Res _v3;
    Iron_List_Iron_Res _v4 = Iron_List_Iron_Res_create();
    _v3 = _v4;
    Iron_List_Iron_Res _v5 = _v3;
    Iron_List_Iron_Res_push(&_v3, /* Res */ (Iron_Res){ .n = _v1 });
    Iron_List_Iron_Res _v9 = _v3;
    return _v9;
}

void Iron_grow(Iron_List_int64_t *_v1, int64_t _v2) {
    int64_t _v9;
    Iron_List_int64_t _v11;
entry_b1:;
    Iron_List_int64_t _v3;
    _v3 = *_v1;
    int64_t _v5;
    _v5 = ((int64_t)0LL);
    goto while_header_6_b2;
    while_header_6_b2:;
    while (1) {
        _v9 = Iron_range(_v2);
        if (!( _v5 < _v9 )) break;
        while_body_7_b3:;
        _v11 = _v3;
        Iron_List_int64_t_push(&_v3, _v5);
        _v5 = (_v5 + ((int64_t)1LL));
        continue;
    }
    goto while_exit_8_b4;
while_exit_8_b4:;
    goto return_exit_9_b5;
return_exit_9_b5:;
    Iron_List_int64_t _v18 = _v3;
    *_v1 = _v18;
    return;
}

void Iron_main(void) {
entry_b1:;
    Iron_List_int64_t _v1;
    int8_t _v2 = (int64_t)1LL;
    int8_t _v3 = (int64_t)2LL;
    Iron_List_int64_t _v4 = Iron_List_int64_t_create();
    Iron_List_int64_t_push(&_v4, ((int64_t)_v2));
    Iron_List_int64_t_push(&_v4, ((int64_t)_v3));
    _v1 = _v4;
    Iron_List_int64_t _v5 = _v1;
    Iron_List_int64_t _v7 = Iron_List_int64_t_clone(&_v1);
    Iron_List_int64_t _v8 = _v1;
    Iron_List_int64_t_push(&_v1, ((int64_t)3LL));
    Iron_String _v12 = iron_string_from_literal("copy: ", 6);
    Iron_List_int64_t _v13 = _v1;
    int64_t _v15 = Iron_List_int64_t_len(&_v1);
    Iron_String _v16 = iron_string_from_literal(" ", 1);
    int64_t _v18 = Iron_List_int64_t_len(&_v7);
    Iron_String _v19;
    {
        int _interp_len_19 = snprintf(NULL, 0, "%s%lld%s%lld", iron_string_cstr(&_v12), (long long)(_v15), iron_string_cstr(&_v16), (long long)(_v18));
        char *_interp_buf_19 = (char *)malloc((size_t)(_interp_len_19 + 1));
        if (!_interp_buf_19) iron_oom_abort("emit_c interp string");
        snprintf(_interp_buf_19, (size_t)(_interp_len_19 + 1), "%s%lld%s%lld", iron_string_cstr(&_v12), (long long)(_v15), iron_string_cstr(&_v16), (long long)(_v18));
        _v19 = iron_string_from_cstr(_interp_buf_19, (size_t)_interp_len_19);
        free(_interp_buf_19);
    }
    Iron_println(_v19);
    Iron_List_int64_t _v22 = _v1;
    Iron_List_int64_t _v24 = Iron_List_int64_t_take(&_v1);
    Iron_String _v25 = iron_string_from_literal("take: ", 6);
    Iron_List_int64_t _v26 = _v1;
    int64_t _v28 = Iron_List_int64_t_len(&_v1);
    Iron_String _v29 = iron_string_from_literal(" ", 1);
    int64_t _v31 = Iron_List_int64_t_len(&_v24);
    Iron_String _v32;
    {
        int _interp_len_32 = snprintf(NULL, 0, "%s%lld%s%lld", iron_string_cstr(&_v25), (long long)(_v28), iron_string_cstr(&_v29), (long long)(_v31));
        char *_interp_buf_32 = (char *)malloc((size_t)(_interp_len_32 + 1));
        if (!_interp_buf_32) iron_oom_abort("emit_c interp string");
        snprintf(_interp_buf_32, (size_t)(_interp_len_32 + 1), "%s%lld%s%lld", iron_string_cstr(&_v25), (long long)(_v28), iron_string_cstr(&_v29), (long long)(_v31));
        _v32 = iron_string_from_cstr(_interp_buf_32, (size_t)_interp_len_32);
        free(_interp_buf_32);
    }
    Iron_println(_v32);
    Iron_grow(&_v1, ((int64_t)100LL));
    Iron_String _v38 = iron_string_from_literal("grow: ", 6);
    Iron_List_int64_t _v39 = _v1;
    int64_t _v41 = Iron_List_int64_t_len(&_v1);
    Iron_String _v42 = iron_string_from_literal(" ", 1);
    Iron_List_int64_t _v43 = _v1;
    if ((uint64_t)((int64_t)99LL) >= (uint64_t)_v43.count) iron_panic_index_oob(__FILE__, __LINE__, ((int64_t)99LL), _v43.count);
    int64_t _v45 = _v43.items[((int64_t)99LL)];
    Iron_String _v46;
    {
        int _interp_len_46 = snprintf(NULL, 0, "%s%lld%s%lld", iron_string_cstr(&_v38), (long long)(_v41), iron_string_cstr(&_v42), (long long)(_v45));
        char *_interp_buf_46 = (char *)malloc((size_t)(_interp_len_46 + 1));
        if (!_interp_buf_46) iron_oom_abort("emit_c interp string");
        snprintf(_interp_buf_46, (size_t)(_interp_len_46 + 1), "%s%lld%s%lld", iron_string_cstr(&_v38), (long long)(_v41), iron_string_cstr(&_v42), (long long)(_v45));
        _v46 = iron_string_from_cstr(_interp_buf_46, (size_t)_interp_len_46);
        free(_interp_buf_46);
    }
    Iron_println(_v46);
    Iron_List_Iron_Res _v51 = Iron_make(((int64_t)2LL));
    Iron_String _v52 = iron_string_from_literal("made: ", 6);
    int64_t _v55 = _v51.items[iron_bounds_idx(((int64_t)0LL), (int64_t)_v51.count, __FILE__, __LINE__)].n;
    Iron_String _v56;
    {
        int _interp_len_56 = snprintf(NULL, 0, "%s%lld", iron_string_cstr(&_v52), (long long)(_v55));
        char *_interp_buf_56 = (char *)malloc((size_t)(_interp_len_56 + 1));
        if (!_interp_buf_56) iron_oom_abort("emit_c interp string");
        snprintf(_interp_buf_56, (size_t)(_interp_len_56 + 1), "%s%lld", iron_string_cstr(&_v52), (long long)(_v55));
        _v56 = iron_string_from_cstr(_interp_buf_56, (size_t)_interp_len_56);
        free(_interp_buf_56);
    }
    Iron_println(_v56);
    Iron_Bag _v59;
    Iron_Bag _v60;
    Iron_Bag _v61 = _v60;
    Iron_Bag _v63 = Iron_bag_init(&_v60);
    _v59 = _v63;
    Iron_List_Iron_Res _v66 = Iron_make(((int64_t)3LL));
    Iron_Bag _v67 = _v59;
    Iron_List_Iron_Res _v68 = _v67.items;
    Iron_List_Iron_Res_free(&((*&_v59).items));
    Iron_Bag _v71 = _v59;
    (*&_v59).items = _v66;
    Iron_String _v72 = iron_string_from_literal("replaced", 8);
    Iron_println(_v72);
    Iron_Inv _v75;
    Iron_Inv _v76;
    Iron_Inv _v77 = _v76;
    Iron_Inv _v79 = Iron_inv_init(&_v76);
    _v75 = _v79;
    Iron_String _v80 = iron_string_from_literal("pub: ", 5);
    Iron_Inv _v81 = _v75;
    Iron_List_int64_t _v82 = _v81.counts;
    int64_t _v84 = Iron_List_int64_t_len(&((*&_v75).counts));
    Iron_String _v85 = iron_string_from_literal(" ", 1);
    Iron_Inv _v86 = _v75;
    Iron_List_int64_t _v87 = _v86.counts;
    if ((uint64_t)((int64_t)1LL) >= (uint64_t)_v87.count) iron_panic_index_oob(__FILE__, __LINE__, ((int64_t)1LL), _v87.count);
    int64_t _v89 = _v87.items[((int64_t)1LL)];
    Iron_String _v90;
    {
        int _interp_len_90 = snprintf(NULL, 0, "%s%lld%s%lld", iron_string_cstr(&_v80), (long long)(_v84), iron_string_cstr(&_v85), (long long)(_v89));
        char *_interp_buf_90 = (char *)malloc((size_t)(_interp_len_90 + 1));
        if (!_interp_buf_90) iron_oom_abort("emit_c interp string");
        snprintf(_interp_buf_90, (size_t)(_interp_len_90 + 1), "%s%lld%s%lld", iron_string_cstr(&_v80), (long long)(_v84), iron_string_cstr(&_v85), (long long)(_v89));
        _v90 = iron_string_from_cstr(_interp_buf_90, (size_t)_interp_len_90);
        free(_interp_buf_90);
    }
    Iron_println(_v90);
    Iron_String _v93 = iron_string_from_literal("end", 3);
    Iron_println(_v93);
    goto drop_cleanup_11_b3;
return_exit_10_b2:;
    Iron_List_int64_t_free(&_v1);
    Iron_List_int64_t_free(&_v7);
    Iron_List_int64_t_free(&_v24);
    Iron_List_Iron_Res_free(&_v51);
    return;
drop_cleanup_11_b3:;
    Iron_Inv_drop(&_v75);
    Iron_Bag_drop(&_v59);
    goto return_exit_10_b2;
}

int main(int argc, char** argv) {
    iron_runtime_init(argc, argv);
    Iron_main();
    iron_runtime_shutdown();
    return 0;
}
