/*
 * iron.lock reader and writer.
 *
 * Format:
 *   # This file is auto-generated by iron. Do not edit manually.
 *   lock_version = 1
 *
 *   [[package]]
 *   name    = "dep-a"
 *   version = "0.1.0"
 *   git     = "owner/dep-a"
 *   sha     = "a1b2c3..."
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>
#include <stdbool.h>

#include "pkg/lockfile.h"

/* ── Helpers ───────────────────────────────────────────────────────────── */

/* Trim leading and trailing whitespace in-place. */
static char *lock_trim(char *s) {
    while (*s && isspace((unsigned char)*s)) s++;
    char *end = s + strlen(s);
    while (end > s && isspace((unsigned char)*(end - 1))) end--;
    *end = '\0';
    return s;
}

/* Extract a quoted string value from a line like:  name = "iron-ecs"
 * Returns malloc'd string, or NULL if not a valid quoted value. */
static char *lock_extract_value(const char *line) {
    const char *eq = strchr(line, '=');
    if (!eq) return NULL;
    eq++;

    /* Skip whitespace */
    while (*eq && isspace((unsigned char)*eq)) eq++;

    if (*eq != '"') return NULL;
    eq++; /* skip opening quote */

    const char *end = strchr(eq, '"');
    if (!end) return NULL;

    size_t len = (size_t)(end - eq);
    char *result = (char *)malloc(len + 1);
    if (!result) return NULL;
    memcpy(result, eq, len);
    result[len] = '\0';
    return result;
}

/* qsort comparator: sort IronLockEntry by name */
static int entry_cmp(const void *a, const void *b) {
    const IronLockEntry *ea = (const IronLockEntry *)a;
    const IronLockEntry *eb = (const IronLockEntry *)b;
    if (!ea->name && !eb->name) return 0;
    if (!ea->name) return -1;
    if (!eb->name) return 1;
    return strcmp(ea->name, eb->name);
}

/* Portable case-insensitive string comparison. */
static int strcasecmp_portable(const char *a, const char *b) {
    while (*a && *b) {
        int ca = tolower((unsigned char)*a);
        int cb = tolower((unsigned char)*b);
        if (ca != cb) return ca - cb;
        a++;
        b++;
    }
    return tolower((unsigned char)*a) - tolower((unsigned char)*b);
}

/* ── Public API ────────────────────────────────────────────────────────── */

int lockfile_read(const char *path, IronLockEntry **out_entries) {
    *out_entries = NULL;

    FILE *f = fopen(path, "r");
    if (!f) return 0; /* file doesn't exist — not an error */

    int capacity = 8;
    int count = 0;
    IronLockEntry *entries = (IronLockEntry *)calloc((size_t)capacity,
                                                      sizeof(IronLockEntry));
    if (!entries) {
        fclose(f);
        return -1;
    }

    bool version_seen = false;
    char line[1024];

    while (fgets(line, (int)sizeof(line), f)) {
        /* Strip trailing newline */
        size_t len = strlen(line);
        while (len > 0 && (line[len - 1] == '\n' || line[len - 1] == '\r'))
            line[--len] = '\0';

        /* Strip comments */
        char *hash = strchr(line, '#');
        if (hash) *hash = '\0';

        char *s = lock_trim(line);
        if (*s == '\0') continue;

        /* Check for lock_version */
        if (!version_seen && strncmp(s, "lock_version", 12) == 0) {
            char *val = lock_extract_value(s);
            if (!val) {
                /* Try bare value: lock_version = 1 */
                const char *eq = strchr(s, '=');
                if (eq) {
                    eq++;
                    while (*eq && isspace((unsigned char)*eq)) eq++;
                    if (*eq != '1' || (*(eq + 1) && !isspace((unsigned char)*(eq + 1)))) {
                        fprintf(stderr, "error: unsupported lock_version\n");
                        free(entries);
                        fclose(f);
                        return -1;
                    }
                }
            } else {
                if (strcmp(val, "1") != 0) {
                    fprintf(stderr, "error: unsupported lock_version '%s'\n", val);
                    free(val);
                    free(entries);
                    fclose(f);
                    return -1;
                }
                free(val);
            }
            version_seen = true;
            continue;
        }

        /* [[package]] header */
        if (strcmp(s, "[[package]]") == 0) {
            if (count >= capacity) {
                capacity *= 2;
                IronLockEntry *new_entries = (IronLockEntry *)realloc(
                    entries, sizeof(IronLockEntry) * (size_t)capacity);
                if (!new_entries) {
                    lockfile_free(entries, count);
                    fclose(f);
                    return -1;
                }
                entries = new_entries;
            }
            memset(&entries[count], 0, sizeof(IronLockEntry));
            count++;
            continue;
        }

        /* Key = value lines (only valid inside a [[package]] block) */
        if (count > 0) {
            IronLockEntry *cur = &entries[count - 1];

            if (strncmp(s, "name", 4) == 0 && (s[4] == ' ' || s[4] == '=')) {
                free(cur->name);
                cur->name = lock_extract_value(s);
            } else if (strncmp(s, "version", 7) == 0 && (s[7] == ' ' || s[7] == '=')) {
                free(cur->version);
                cur->version = lock_extract_value(s);
            } else if (strncmp(s, "git", 3) == 0 && (s[3] == ' ' || s[3] == '=')) {
                free(cur->git);
                cur->git = lock_extract_value(s);
            } else if (strncmp(s, "sha", 3) == 0 && (s[3] == ' ' || s[3] == '=')) {
                free(cur->sha);
                cur->sha = lock_extract_value(s);
            }
        }
    }

    fclose(f);
    *out_entries = entries;
    return count;
}

void lockfile_write(const char *path, IronLockEntry *entries, int count) {
    FILE *f = fopen(path, "w");
    if (!f) return;

    /* Sort alphabetically by name */
    if (count > 1) {
        qsort(entries, (size_t)count, sizeof(IronLockEntry), entry_cmp);
    }

    fprintf(f, "# This file is auto-generated by iron. Do not edit manually.\n\n");
    fprintf(f, "lock_version = 1\n");

    for (int i = 0; i < count; i++) {
        fprintf(f, "\n[[package]]\n");
        fprintf(f, "name    = \"%s\"\n", entries[i].name ? entries[i].name : "");
        fprintf(f, "version = \"%s\"\n", entries[i].version ? entries[i].version : "");
        fprintf(f, "git     = \"%s\"\n", entries[i].git ? entries[i].git : "");
        fprintf(f, "sha     = \"%s\"\n", entries[i].sha ? entries[i].sha : "");
    }

    fclose(f);
}

void lockfile_free(IronLockEntry *entries, int count) {
    if (!entries) return;
    for (int i = 0; i < count; i++) {
        free(entries[i].name);
        free(entries[i].version);
        free(entries[i].git);
        free(entries[i].sha);
    }
    free(entries);
}

IronLockEntry *lockfile_find(IronLockEntry *entries, int count,
                             const char *git) {
    if (!entries || !git) return NULL;
    for (int i = 0; i < count; i++) {
        if (entries[i].git && strcasecmp_portable(entries[i].git, git) == 0) {
            return &entries[i];
        }
    }
    return NULL;
}
